FROM python:3.13-slim-bullseye

RUN apt update \
&& apt -y install libpq-dev gcc curl
# Set separate working directory for easier debugging.
WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set up layer caching for pip/uv
ENV UV_LINK_MODE=copy

# Install requirements separately
# to take advantage of layer caching.
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen --no-install-project

# Set up dataform-related dependencies.
# RUN --mount=type=cache,target=/root/.cache/uv uv pip install --system dataform-postgres

# Copy everything. (Note: If needed, we can use .dockerignore to limit what's copied.)
COPY . .

# Install the project and all dependencies.
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen
