config {
    type: "incremental",
    schema: "schama",
    tags: [
        "test"
    ],
    description: "test sqlx file for lint by sqlfluff-templater-dataform.",
    columns: {
        user_id: "some user_id description",
        name: "some name description",
        age: "some age description",
        order_date: "some order_date description",
        order_count: "some order_count description"
    }
}

WITH users AS (
    SELECT
        user_id,
        name,
        age
    FROM ${ref("users")}
),

user_orders AS (
    SELECT
        user_id,
        order_id,
        DATE(created_at) AS order_date
    FROM ${ref('user_orders')}
)

SELECT
    users.user_id,
    name,
    age,
    order_date,
    COUNT(order_id) AS order_count
FROM users LEFT OUTER JOIN user_orders ON users.user_id = user_orders.user_id
WHERE TRUE
${when(incremental(), `AND users.updated_at > (SELECT MAX(updated_at) FROM ${self()})`)}
GROUP BY user_id, name, age, order_date
