config {
    type: "incremental",
    schema: "schama",
    tags: [
        "test"
    ],
    description: "test sqlx file for lint by sqlfluff-templater-dataform.",
    columns: {
        user_id: "ユーザーID",
        name: "ユーザー名",
        age: "年齢",
        order_date: "注文日",
        order_count: "注文回数"
    }
}

js {
  const { currentDate } = new Date().toISOString().split('T')[0];
}

WITH users AS (
    SELECT
        user_id,
        name,
        age
    FROM ${ref("users")}
),

user_orders AS (
    SELECT
        user_id,
        order_id,
        DATE(created_at) AS order_date
    FROM ${ref('user_orders')}
)

SELECT
    users.user_id,
    name,
    age,
    order_date,
    COUNT(order_id) AS order_count
FROM users LEFT OUTER JOIN user_orders ON users.user_id = user_orders.user_id
WHERE TRUE
${when(incremental(), `WHERE users.updated_at > (SELECT MAX(updated_at) FROM ${self()})`)}
GROUP
BY
    user_id, name,
    age, order_date
